[
    [
        916657, 
        "dnf remove wants to downgrade packages; fails on transaction check"
    ], 
    [
        921294, 
        "dnf downgrade failure"
    ], 
    [
        922521, 
        "DNF crashes when passing packages to it via pipe"
    ], 
    [
        926871, 
        "[abrt] download_packages:AttributeError: 'Repo' object has no attribute 'cache'"
    ], 
    [
        878826, 
        "[rfe] dnf could use systemd timer unit rather than crontabs"
    ], 
    [
        922664, 
        "an option for disabling the regular metadata sync"
    ], 
    [
        892064, 
        "hourly dnf makecache too frequent, also consider using ionice"
    ], 
    [
        919769, 
        "dnf runs makecache hourly despite laptop power state"
    ], 
    [
        947258, 
        "dnf doesn't erase excluded packages"
    ], 
    [
        889202, 
        "[rfe] [repos] add support for skip_if_unavailable in repository config"
    ], 
    [
        923384, 
        "DNF uses yum web signature"
    ], 
    [
        950722, 
        "[abrt] dnf-0.3.2-1.gitf3818b4.fc20: queries.py:179:_construct_result:AttributeError: 'NoneType' object has no attribute 'query'"
    ], 
    [
        903775, 
        "Update command is deprecated but nomenclature still being used"
    ], 
    [
        887317, 
        "Dnf should beter report upgrades via obsoletes."
    ], 
    [
        914919, 
        "DNF does not have   group install"
    ], 
    [
        922667, 
        "the cronned 'dnf makecache' runs should give up quickly if there's network/checksumming issues"
    ], 
    [
        958452, 
        "dnf update Produces Log Messages Involving \"ts_done state\""
    ], 
    [
        959990, 
        "dnf dist-sync recommended in manual page but is missing from dnf's command line options"
    ], 
    [
        961549, 
        "[abrt] dnf-0.3.4-1.git03fd687.fc19: __init__.py:826:perform:Exception: (10, 'Error HTTP/FTP status code: 404', 404)"
    ], 
    [
        962188, 
        "obsoletes sometimes result in \"ERROR with transaction check vs depsolve\""
    ], 
    [
        966372, 
        "dnf prints an empty python list after running without root privileges"
    ], 
    [
        965410, 
        "\"dnf clean expire-cache\" does not have any effect"
    ], 
    [
        963627, 
        "dnf shows way over 100% in its progress bar"
    ], 
    [
        965114, 
        "When running dnf using file:/// as the media, it tries to erase packages in file:///"
    ], 
    [
        964467, 
        "group install is broken"
    ], 
    [
        963680, 
        "dnf dies with a traceback during update"
    ], 
    [
        963133, 
        "name is misprinted when package is not found"
    ], 
    [
        916662, 
        "dnf remove wants to install new packages"
    ], 
    [
        967732, 
        "[abrt] dnf-0.3.6-1.git24ce938.fc19: __init__.py:364:hashopen:DBNoSuchFileError: (2, 'Datei oder Verzeichnis nicht gefunden')"
    ], 
    [
        908491, 
        "[rfe] list recent"
    ], 
    [
        968159, 
        "repo_rpmmd.c: base:xml attr in <location> is ignored"
    ], 
    [
        974427, 
        "dnf fails on all commands with fatal error: \"global name 'os' is not defined\""
    ], 
    [
        974866, 
        "dnf crashes if neither baseurl nor mirrorlist are defined"
    ], 
    [
        976652, 
        "[abrt] UnicodeEncodeError with 'dnf info checkpolicy'"
    ], 
    [
        975858, 
        "dnf can't install in an empty installroot"
    ], 
    [
        964584, 
        "dnf doesn't replace $releasever/$basearch in mirror url"
    ], 
    [
        979942, 
        "[abrt] cli.py:1015:_configure_repos:KeyError: <repo id>"
    ], 
    [
        980227, 
        "[locking] OSError when a long running transaction gets metadata files written over by a concurrent 'dnf makecache'"
    ], 
    [
        981310, 
        "NameError: global name 'to_utf8' is not defined"
    ], 
    [
        977661, 
        "[abrt] Ctrl+C ends up with a TypeError traceback involving Base.__exit__() and Repo._handle_load()"
    ], 
    [
        984483, 
        "default to skip_if_unavailable=True"
    ], 
    [
        986545, 
        "dnf mismatching it's librepo dep in rawhide"
    ], 
    [
        979042, 
        "Slow download of packages"
    ], 
    [
        977753, 
        "Repository \"@System\" instead of \"fedora\""
    ], 
    [
        996138, 
        "[abrt] install_grouplist:UnicodeDecodeError during 'dnf group install'"
    ], 
    [
        993916, 
        "'upgrade' command displays old version numbers in summary, rather than new version numbers"
    ], 
    [
        1002798, 
        "Error when checking librepo explicit requires"
    ], 
    [
        997403, 
        "Error message instructs users to invoke 'yum' rather than 'dnf' to fix a problem"
    ], 
    [
        1002508, 
        "Updated to install any packages \"An Curl handle error: Unsupported protocol\""
    ], 
    [
        1006366, 
        "dnf makecache runs on LiveCD"
    ], 
    [
        1008444, 
        "confusing message when removing packages"
    ], 
    [
        1003220, 
        "[abrt] dnf-0.3.11-1.git7d717c7.fc19: output.py:838:_enc:TypeError: object of type 'NoneType' has no len()"
    ], 
    [
        998859, 
        "\"dnf upgrade --best\" will always install 64bits package when 32bit package is installed"
    ], 
    [
        909744, 
        "[rfe] support parallel downloads"
    ], 
    [
        984529, 
        "[rfe] fastest mirror"
    ], 
    [
        967798, 
        "[RFE] repositories costs"
    ], 
    [
        995459, 
        "conflicting requests when trying to install locally available packages"
    ], 
    [
        1013764, 
        "DNF group remove doesn't work"
    ], 
    [
        1013773, 
        "DNF group info doesn't work"
    ], 
    [
        1017278, 
        "dnf does not notice file conflicts"
    ], 
    [
        1021087, 
        "traceback during download after a transaction with obsoletes"
    ], 
    [
        878348, 
        "'dnf history undo' support missing"
    ], 
    [
        880524, 
        "[kernel] managing multiple kernel packages"
    ], 
    [
        1019957, 
        "'dnf groups summary' traceback (global name 'patterns' is not defined)"
    ], 
    [
        1020101, 
        "'dnf grouplist' throws NameError"
    ], 
    [
        1020934, 
        "traceback in \"dnf repolist\""
    ], 
    [
        1023486, 
        "groups operations failing due to a libcomps API change in its latest version (KeyError: 'en_US.UTF-8')"
    ], 
    [
        1019170, 
        "handling wildcards in the version"
    ], 
    [
        1024776, 
        "librepo version mismatch (no attribute 'LRO_FASTESTMIRRORCACHE')"
    ], 
    [
        1025650, 
        "[abrt] dnf-0.4.6-1.fc20: i18n.py:119:ucd:UnicodeEncodeError: 'ascii' codec can't encode character u'\\xe9' in position 51: ordinal not in range(128)"
    ], 
    [
        1014563, 
        "Support Python 3 in DNF"
    ], 
    [
        1029948, 
        "dnf does not show all desktop environments in dnf groups list output"
    ], 
    [
        1030998, 
        "install doesn't work for '*/binaryname' patterns"
    ], 
    [
        1030297, 
        "dnf doesn't support http urls"
    ], 
    [
        1030980, 
        "dnf downgrade PACKAGE, misleading message about possible typo if PACKAGE is not installed"
    ], 
    [
        884615, 
        "RFE: Provide list of packages installed on top of the system"
    ], 
    [
        963137, 
        "[rfe] perform complex packaging operations as a CLI user"
    ], 
    [
        991038, 
        "lacks history rollback"
    ], 
    [
        1032455, 
        "[abrt] dnf-0.4.7-1.fc20: decoder.py:383:raw_decode:ValueError: No JSON object could be decoded"
    ], 
    [
        1034607, 
        "dnf does not work with media repo"
    ], 
    [
        1036116, 
        "dnf install failed with exception"
    ], 
    [
        967264, 
        "[plugins] Support post-transaction actions"
    ], 
    [
        1018284, 
        "[rfe] [api] refactor check for valid id into separate function"
    ], 
    [
        1035164, 
        "[abrt] dnf-0.4.7-1.fc20: miscutils.py:61:checkSig:OSError: [Errno 2] Adres\u00e1\u0159 nebo soubor neexistuje: '/var/cache/dnf/x86_64/20/updates-testing/packages/kernel-3.11.9-300.fc20.x86_64.rpm'"
    ], 
    [
        1036147, 
        "[locking] Traceback for dnf search if running under su - USER"
    ], 
    [
        1036211, 
        "Install groups using @ sign"
    ], 
    [
        1038403, 
        "[abrt] dnf-0.4.9-1.fc20: base.py:1832:handle_erase:AssertionError"
    ], 
    [
        1038937, 
        "[plugins] [api] Add hook for metadata download complete event"
    ], 
    [
        1040255, 
        "dnf show wrong Installed size when  install  packages"
    ], 
    [
        1044502, 
        "[abrt] dnf: base.py:125:_add_repo_to_sack:UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 113: ordinal not in range(128)"
    ], 
    [
        1044981, 
        "[doc] [rfe] support setopt"
    ], 
    [
        1044999, 
        "[doc] show dependencies during update"
    ], 
    [
        1048402, 
        "[abrt] dnf: cli.py:1521:search:AttributeError: 'module' object has no attribute 'exception'"
    ], 
    [
        1048572, 
        "dnf resolve failure"
    ], 
    [
        1048716, 
        "man page does not mention sub command remove"
    ], 
    [
        1048719, 
        "Minor error in 'dnf --help', using the package name Yum instead of dnf"
    ], 
    [
        1048988, 
        "[plugins] [api] add a hook for MD refresh"
    ], 
    [
        1045737, 
        "[RFE] 'throttle' option."
    ], 
    [
        1048468, 
        "dnf --cacheonly list installed tries to download repodata"
    ], 
    [
        1048488, 
        "AssertionError on invalid error log level"
    ], 
    [
        1049025, 
        "Incorrect dependency check on removal"
    ], 
    [
        1051554, 
        "disable fastestmirror by default (and make it configurable)"
    ], 
    [
        1030440, 
        "[RFE] bash completion support"
    ], 
    [
        1046244, 
        "dnf doesn't keep the downloaded packages in the cache"
    ], 
    [
        1055051, 
        "things like ' dnf install \"kernel-devel-uname-r = 3.12.8-300.fc20.x86_64\" ' don't work"
    ], 
    [
        1056400, 
        "DNF not support url installation for a package"
    ], 
    [
        1060522, 
        "dnf says \"Nothing to do\" instead of \"Error: broken dependencies.\""
    ], 
    [
        909468, 
        "[rfe] delta rpm support"
    ], 
    [
        1062390, 
        "dnf.rpmUtils.arch.getBaseArch() doesn't return identical results to yum's rpmUtils.arch.getBaseArch()"
    ], 
    [
        1062847, 
        "dnf man page errors"
    ], 
    [
        1063022, 
        "[abrt] dnf: i18n.py:38:write:UnicodeEncodeError: 'ascii' codec can't encode character u'\\xe9' in position 12: ordinal not in range(128)"
    ], 
    [
        1064148, 
        "DNF attempts to remove packages from local file-based repository"
    ], 
    [
        1048788, 
        "[abrt] dnf: __init__.py:183:install:ArchException: Used arch is unknown."
    ], 
    [
        1065728, 
        "[doc] Metadata expire configurable per repository"
    ], 
    [
        1065879, 
        "[API] provides is missing in queries documentation"
    ], 
    [
        1065959, 
        "bash-completion should use \"distro-sync\" as the preferred completion for dnf"
    ], 
    [
        1066743, 
        "[doc] `dnf clean` should function or warn when run as normal user"
    ], 
    [
        1069996, 
        "[abrt] dnf: repo.py:312:start:AttributeError: 'NoneType' object has no attribute 'start'"
    ]
]